### ISSUE TITLE
Process variables as out-exchange's body

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/camunda-bpm-camel#33]
If a route has to process the result of a process instance startet by the route itself it would be convenient if the process instance's variables were set as body of the out exchange. Of course one has to be aware of building processes which end in expected wait states (end event, async flags, receive task, external task, etc.).

Pull request is coming soon...

**Comment by berndruecker** [comment]
Damn it - I should have merged this yesterday - than it would have been closed exactly 4 years after creation :-)
