### ISSUE TITLE
Question: Why is this project deprecated?

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-bpm-camel#66]
I was planning on using camunda with camel for some time and now have a concrete use case for async external tasks ... and see the badge "deprecated".

@berndruecker  may be you can answer this: What is the state of this project?

**Comment by berndruecker** [comment]
Hey Jan. I think the best description of the lifecycle is somewhat "not actively maintained, but ready-to-use whenever it works for your environment" - so deprecated does not sound right. I agree.

Unmaintained would also work, but is probably not any better.

I am a bit hesitant to set it to "stable" or what do you think?

**Comment by jangalinski** [comment]
Well, it is the first time I try this out ... give me a moment until I'd call it "stable".

But maybe I will start working on issues and add features on my journey. For now, your answer is sufficient, thanks!

**Comment by celanthe** [comment]
Hi @berndruecker and @jangalinski -- Thanks so much for your pull requests to this project, Jan. It's much appreciated. As to the 'deprecated' lifecycle badge, I agree with your assessment. I am happy to update this project's lifecycle badge to 'Incubating,' if you feel that would work better. As this extension still seems to work fairly well [or would once it got some necessary upgrades to bring it up to date w/the latest version of Camunda, a contributor guide, etc.] I can absolutely see your point re: its lifecycle status. If you're comfortable with me adding an, ['Incubating,' badge](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md#incubating-), I can do so. 

Stable badges are reserved for projects with an active community, a current maintainer, and more. The criteria for upgrading an extension to 'stable' lifecycle status can be found at: https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md#stable-

Thank you again for your contributions and thoughts. I look forward to the evolution of this project.


There was previous discussion back in the early, early days of the Community Hub as to this particular extension, and at the time it was unmaintained with 2 year old issues that had no response as its prior maintainers had moved on from the technology and were now in different roles.
