### ISSUE TITLE
pipeline fails on snapshot release

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-bpm-camel#82]
see: https://github.com/camunda-community-hub/camunda-bpm-camel/runs/4896841085?check_suite_focus=true

we get

```
Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (default-deploy) on project camunda-bpm-camel-spring: Failed to deploy artifacts: Could not transfer artifact org.camunda.bpm.extension.camel:camunda-bpm-camel:pom:0.9.0-20220121.132151-1 from/to camunda-nexus (https://app.camunda.com/nexus/content/repositories/camunda-bpm-community-extensions-snapshots): authentication failed for https://app.camunda.com/nexus/content/repositories/camunda-bpm-community-extensions-snapshots/org/camunda/bpm/extension/camel/camunda-bpm-camel/0.9.0-SNAPSHOT/camunda-bpm-camel-0.9.0-20220121.132151-1.pom, **status: 401 Unauthorized** -> [Help 1]
```

I copied the standard actions from camunda-bpm-mockito, so I guess its just missing secrets on this repo.

@celanthe  , can you take care of this?

**Comment by celanthe** [comment]
Hi @jangalinski -- I've added this repository to our internal infrastructure. The necessary secrets should populate into the repository now, which should resolve the issue you're seeing here. Please let me know if that doesn't work! :)

**Comment by celanthe** [comment]
Hi @jangalinski -- I just wanted to check back in on this and see if everything was resolved? I hadn't heard back from you. Thank you kindly! :)
